### ISSUE TITLE
Broken images README

### ISSUE THREAD

**Issue by iondrimba** [graypegg/chromatism#47]
Hi there!

Is there any interest in fixing those broken images located throughout the README?
![annotation 2019-03-06 205852](https://user-images.githubusercontent.com/178548/53922632-e6ca6d80-4053-11e9-855a-3bec1eb439cf.png)
I could help.

**Comment by toish** [comment]
I have the source file for these! Not sure why they fell off Github's CDN, but I'll try to fix that ASAP

**Comment by iondrimba** [comment]
Thanks @toish 👍

**Comment by iondrimba** [comment]
Apparently everything is working again @graypegg 

![Screenshot from 2020-04-13 13-23-14](https://user-images.githubusercontent.com/178548/79137922-00c39d00-7d8a-11ea-81e1-4d4bdd1412e5.png)
