### ISSUE TITLE
Broken images on documentation

### ISSUE THREAD

**Issue by stebogit** [graypegg/chromatism#51]
Hi, for some reason all the pictures in the documentations are just broken, therefore the docs are almost useless 😭 
Is it just the CSN server temporarily down or is it permanently not available anymore? 🤕 

![Screen Shot 2022-01-11 at 3 03 31 PM](https://user-images.githubusercontent.com/12717225/149035215-97cbdac3-cd23-4fa7-9008-816fb2e35764.png)

Is there a demo site maybe as an alternative?

**Comment by graypegg** [comment]
Fixed! I'm so sorry this has rotted the way in its current state. This was something I originally made for a high school precalc class, and now it's a decade later.

Really hope to clean things up so this is at least functional in a maintenance state.
